### ISSUE TITLE
Local execution of tests is failing

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse-lmos/lmos-operator#32]
When I try to run the tests locally with
```
./gradlew test
```
I get 10 failing tests due to `java.lang.IllegalStateException` with the Spring application context:

```
> Task :test

CustomResourcesControllerIntegrationTest > shouldReturnChannels() FAILED
    java.lang.IllegalStateException at Assert.java:101

CustomResourcesControllerIntegrationTest > shouldReturnNotFound() FAILED
    java.lang.IllegalStateException at Assert.java:101

CustomResourcesControllerIntegrationTest > shouldReturnChannelResource() FAILED
    java.lang.IllegalStateException at Assert.java:101

CustomResourcesControllerIntegrationTest > shouldReturnChannelRoutingResource() FAILED
    java.lang.IllegalStateException at Assert.java:101

CustomResourcesControllerIntegrationTest > executionError FAILED
    java.lang.IllegalStateException at Assert.java:101

ChannelReconcilerTest > shouldCreateUnresolvedChannelRouting() FAILED
    java.lang.IllegalStateException at Assert.java:101

ChannelReconcilerTest > shouldCreateUnresolvedChannelRoutingForNotMatchingTenant() FAILED
    java.lang.IllegalStateException at Assert.java:101

ChannelReconcilerTest > shouldCreateResolvedChannelRouting() FAILED
    java.lang.IllegalStateException at Assert.java:101

ChannelReconcilerTest > verifyThatCRDAreCreated() FAILED
    java.lang.IllegalStateException at Assert.java:101

ChannelReconcilerTest > executionError FAILED
    java.lang.IllegalStateException at Assert.java:101

31 tests completed, 10 failed
```

Does anybody know what could cause this?

FTR, the full exception is:
```
java.lang.IllegalStateException: The ApplicationContext loaded for [WebMergedContextConfiguration@5ab2c5d8 testClass = ai.ancf.lmos.operator.reconciler.ChannelReconcilerTest, locations = [], classes = [ai.ancf.lmos.operator.OperatorApplication], contextInitializerClasses = [], activeProfiles = [], propertySourceDescriptors = [], propertySourceProperties = ["spring.main.allow-bean-definition-overriding=true", "org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true"], contextCustomizers = [org.springframework.boot.test.autoconfigure.OnFailureConditionReportContextCustomizerFactory$OnFailureConditionReportContextCustomizer@2a2c13a8, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@1f, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@de42f8b1, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizer@1a7288a3, [ImportsContextCustomizer@5ec75178 key = [io.javaoperatorsdk.operator.springboot.starter.test.TestConfiguration]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@3e5499cc, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@30bcf3c1, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@422c3c7a, org.springframework.boot.test.web.reactive.server.WebTestClientContextCustomizer@531c311e, org.springframework.boot.test.web.reactor.netty.DisableReactorResourceFactoryGlobalResourcesContextCustomizerFactory$DisableReactorResourceFactoryGlobalResourcesContextCustomizerCustomizer@662f5666, org.springframework.test.context.support.DynamicPropertiesContextCustomizer@0, org.springframework.boot.test.context.SpringBootTestAnnotation@9e9aa502], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null] is not active. This may be due to one of the following reasons: 1) the context was closed programmatically by user code; 2) the context was closed during parallel test execution either according to @DirtiesContext semantics or due to automatic eviction from the ContextCache due to a maximum cache size policy.
	at org.springframework.util.Assert.state(Assert.java:101)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:132)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:191)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:130)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:260)
	at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:160)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Comment by kaikreuzer** [comment]
I've created https://github.com/eclipse-lmos/lmos-operator/pull/38 for the time being until the tests are fixed.

**Comment by RobWin** [comment]
I'm working on it.
Seems the Spring Boot TestConfiguration is not setup correctly.

**Comment by kaikreuzer** [comment]
Fixed by #41
